apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customresources.nokube.xyz
spec:
  group: nokube.xyz
  version: v1
  names:
    kind: CustomResource
    singular: customresource
    plural: customresources
    shortNames:
    - crz
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            count:
              type: integer
              minimum: 1
              maximum: 20
