/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	customresourcev1 "github.com/andy2046/k8s-custom-resource-watch/pkg/apis/customresource/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomResources implements CustomResourceInterface
type FakeCustomResources struct {
	Fake *FakeNokubeV1
	ns   string
}

var customresourcesResource = schema.GroupVersionResource{Group: "nokube.xyz", Version: "v1", Resource: "customresources"}

var customresourcesKind = schema.GroupVersionKind{Group: "nokube.xyz", Version: "v1", Kind: "CustomResource"}

// Get takes name of the customResource, and returns the corresponding customResource object, and an error if there is any.
func (c *FakeCustomResources) Get(name string, options v1.GetOptions) (result *customresourcev1.CustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customresourcesResource, c.ns, name), &customresourcev1.CustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customresourcev1.CustomResource), err
}

// List takes label and field selectors, and returns the list of CustomResources that match those selectors.
func (c *FakeCustomResources) List(opts v1.ListOptions) (result *customresourcev1.CustomResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customresourcesResource, customresourcesKind, c.ns, opts), &customresourcev1.CustomResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &customresourcev1.CustomResourceList{ListMeta: obj.(*customresourcev1.CustomResourceList).ListMeta}
	for _, item := range obj.(*customresourcev1.CustomResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customResources.
func (c *FakeCustomResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customresourcesResource, c.ns, opts))

}

// Create takes the representation of a customResource and creates it.  Returns the server's representation of the customResource, and an error, if there is any.
func (c *FakeCustomResources) Create(customResource *customresourcev1.CustomResource) (result *customresourcev1.CustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customresourcesResource, c.ns, customResource), &customresourcev1.CustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customresourcev1.CustomResource), err
}

// Update takes the representation of a customResource and updates it. Returns the server's representation of the customResource, and an error, if there is any.
func (c *FakeCustomResources) Update(customResource *customresourcev1.CustomResource) (result *customresourcev1.CustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customresourcesResource, c.ns, customResource), &customresourcev1.CustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customresourcev1.CustomResource), err
}

// Delete takes name of the customResource and deletes it. Returns an error if one occurs.
func (c *FakeCustomResources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customresourcesResource, c.ns, name), &customresourcev1.CustomResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customresourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &customresourcev1.CustomResourceList{})
	return err
}

// Patch applies the patch and returns the patched customResource.
func (c *FakeCustomResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *customresourcev1.CustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customresourcesResource, c.ns, name, pt, data, subresources...), &customresourcev1.CustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customresourcev1.CustomResource), err
}
