/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/andy2046/k8s-custom-resource-watch/pkg/apis/customresource/v1"
	scheme "github.com/andy2046/k8s-custom-resource-watch/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomResourcesGetter has a method to return a CustomResourceInterface.
// A group's client should implement this interface.
type CustomResourcesGetter interface {
	CustomResources(namespace string) CustomResourceInterface
}

// CustomResourceInterface has methods to work with CustomResource resources.
type CustomResourceInterface interface {
	Create(*v1.CustomResource) (*v1.CustomResource, error)
	Update(*v1.CustomResource) (*v1.CustomResource, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CustomResource, error)
	List(opts metav1.ListOptions) (*v1.CustomResourceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CustomResource, err error)
	CustomResourceExpansion
}

// customResources implements CustomResourceInterface
type customResources struct {
	client rest.Interface
	ns     string
}

// newCustomResources returns a CustomResources
func newCustomResources(c *NokubeV1Client, namespace string) *customResources {
	return &customResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the customResource, and returns the corresponding customResource object, and an error if there is any.
func (c *customResources) Get(name string, options metav1.GetOptions) (result *v1.CustomResource, err error) {
	result = &v1.CustomResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomResources that match those selectors.
func (c *customResources) List(opts metav1.ListOptions) (result *v1.CustomResourceList, err error) {
	result = &v1.CustomResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customResources.
func (c *customResources) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("customresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a customResource and creates it.  Returns the server's representation of the customResource, and an error, if there is any.
func (c *customResources) Create(customResource *v1.CustomResource) (result *v1.CustomResource, err error) {
	result = &v1.CustomResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("customresources").
		Body(customResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a customResource and updates it. Returns the server's representation of the customResource, and an error, if there is any.
func (c *customResources) Update(customResource *v1.CustomResource) (result *v1.CustomResource, err error) {
	result = &v1.CustomResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customresources").
		Name(customResource.Name).
		Body(customResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the customResource and deletes it. Returns an error if one occurs.
func (c *customResources) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customresources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customResources) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customresources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched customResource.
func (c *customResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CustomResource, err error) {
	result = &v1.CustomResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("customresources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
